#!/usr/bin/env python3
"""Generate a C++ header embedding .psc files for MCU playlists.

PlatformIO runs this as a pre-build script. It scans:
  - build/psc/  (local ignored playlist inputs)

The generated header is written under the environment build directory and
added to CPPPATH, so firmware gets the PSC bytes compiled into flash without
requiring a runtime filesystem.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
from typing import Iterable

try:
    _SCRIPT_DIR = Path(__file__).resolve().parent
except NameError:
    # PlatformIO/SCons execs this as a pre-build SConscript, where __file__
    # is not defined. PlatformIO runs from the project root, so the sibling
    # psc_v1 module lives under ./scripts.
    _SCRIPT_DIR = Path.cwd().resolve() / "scripts"
sys.path.insert(0, str(_SCRIPT_DIR))
from psc_v1 import PscValidationError, validate_psc_scene


def _psc_dir(project_dir: Path) -> Path:
    return project_dir / "build" / "psc"


def _find_psc_files(project_dir: Path) -> list[Path]:
    directory = _psc_dir(project_dir)
    if not directory.is_dir():
        return []
    return sorted(directory.rglob("*.psc"))


def _identifier(path: Path, index: int) -> str:
    stem = re.sub(r"[^0-9A-Za-z_]", "_", path.stem)
    if not stem or stem[0].isdigit():
        stem = f"scene_{stem}"
    return f"kEmbeddedPscScene_{index}_{stem}"


def _escape_cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _validate_psc(path: Path, data: bytes) -> str | None:
    try:
        validate_psc_scene(data)
    except PscValidationError as exc:
        return str(exc)
    return None


def _display_config_path(project_dir: Path) -> Path:
    return project_dir / "build" / "display_config.json"


def _load_display_brightness(project_dir: Path) -> int | None:
    path = _display_config_path(project_dir)
    if not path.is_file():
        return None
    error = None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        error = "invalid JSON"
        data = None
    except OSError as exc:
        error = f"could not read display config: {exc}"
        data = None
    if not isinstance(data, dict):
        error = error or "display config must be a JSON object"
    brightness = data.get("brightness") if isinstance(data, dict) else None
    if error is None and (isinstance(brightness, bool) or not isinstance(brightness, int)):
        error = "brightness must be an integer"
    if error is None and (brightness < 0 or brightness > 255):
        error = "brightness must be between 0 and 255"
    if error is not None:
        print(f"warning: ignoring {path}: {error}")
        return None
    return brightness


def _format_bytes(data: bytes) -> Iterable[str]:
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        yield "    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ","


def generate(project_dir: Path, output_header: Path) -> list[Path]:
    project_dir = project_dir.resolve()
    output_header.parent.mkdir(parents=True, exist_ok=True)
    psc_files = _find_psc_files(project_dir)
    display_brightness = _load_display_brightness(project_dir)
    playlist_entries: list[tuple[Path, bytes]] = []
    for path in psc_files:
        data = path.read_bytes()
        error = _validate_psc(path, data)
        if error:
            raise PscValidationError(f"{path}: {error}")
        playlist_entries.append((path, data))

    has_playlist = 1 if playlist_entries else 0
    config_header = output_header.with_name("PscPlaylistConfig.h")

    config_lines = [
        "// Auto-generated by scripts/generate_psc_playlist.py. Do not edit.",
        "#pragma once",
        "",
        f"#define POLAR_SHADER_EMBEDDED_PSC_SCENE_COUNT {len(playlist_entries)}",
        f"#define POLAR_SHADER_HAS_EMBEDDED_PSC_PLAYLIST {has_playlist}",
    ]
    if display_brightness is not None:
        config_lines.append(f"#define POLAR_SHADER_DISPLAY_BRIGHTNESS {display_brightness}")
    config_lines.append("")

    lines: list[str] = [
        "// Auto-generated by scripts/generate_psc_playlist.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#if defined(ARDUINO)",
        "#include <Arduino.h>",
        "#endif",
        "#include \"PscPlaylistConfig.h\"",
        "#include \"composer/EmbeddedPscPlaylist.h\"",
        "",
        "#ifndef POLAR_SHADER_PSC_PROGMEM",
        "#if defined(PROGMEM)",
        "#define POLAR_SHADER_PSC_PROGMEM PROGMEM",
        "#else",
        "#define POLAR_SHADER_PSC_PROGMEM",
        "#endif",
        "#endif",
        "",
        "namespace PolarShader::composer {",
    ]

    table_entries: list[str] = []
    for index, (path, data) in enumerate(playlist_entries):
        symbol = _identifier(path, index)
        rel = path.relative_to(project_dir)
        lines.append(f"inline const uint8_t {symbol}[] POLAR_SHADER_PSC_PROGMEM = {{")
        lines.extend(_format_bytes(data))
        lines.append("};")
        lines.append("")
        table_entries.append(
            f"    {{\"{_escape_cpp_string(str(rel))}\", {symbol}, sizeof({symbol})}},"
        )

    if table_entries:
        lines.append("inline constexpr EmbeddedPscScene kEmbeddedPscSceneTable[] = {")
        lines.extend(table_entries)
        lines.append("};")
        lines.append("inline constexpr const EmbeddedPscScene *kEmbeddedPscScenes = kEmbeddedPscSceneTable;")
        lines.append(
            "inline constexpr std::size_t kEmbeddedPscSceneCount = "
            "sizeof(kEmbeddedPscSceneTable) / sizeof(kEmbeddedPscSceneTable[0]);"
        )
    else:
        lines.append("inline constexpr const EmbeddedPscScene *kEmbeddedPscScenes = nullptr;")
        lines.append("inline constexpr std::size_t kEmbeddedPscSceneCount = 0;")

    lines.append("}")
    lines.append("")
    config_header.write_text("\n".join(config_lines), encoding="utf-8")
    output_header.write_text("\n".join(lines), encoding="utf-8")
    return [path for path, _data in playlist_entries]


def _run_cli() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-dir", default=".")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    files = generate(Path(args.project_dir), Path(args.output))
    print(f"generated {args.output} from {len(files)} .psc file(s)")


def _run_platformio() -> None:
    Import("env")  # type: ignore[name-defined]
    project_dir = Path(env.subst("$PROJECT_DIR"))  # type: ignore[name-defined]
    output_dir = Path(env.subst("$BUILD_DIR")) / "generated"
    output_header = output_dir / "PscPlaylistAssets.h"
    files = generate(project_dir, output_header)
    env.Append(CPPPATH=[str(output_dir)])  # type: ignore[name-defined]
    display_brightness = _load_display_brightness(project_dir)
    if display_brightness is not None:
        env.Append(  # type: ignore[name-defined]
            CPPDEFINES=[("POLAR_SHADER_DISPLAY_BRIGHTNESS", display_brightness)]
        )
        print(f"Embedded display brightness: {display_brightness}")
    print(f"Embedded PSC playlist: {len(files)} file(s) -> {output_header}")


if __name__ == "__main__":
    _run_cli()
elif "Import" in globals():
    _run_platformio()
