#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request
import zipfile


REPO_ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = REPO_ROOT / "web"
SOURCE_ROOT = REPO_ROOT / "src"
SKETCH_ROOT = WEB_ROOT / "sketches"
STAGE_ROOT = WEB_ROOT / ".stage"
DIST_ROOT = WEB_ROOT / "dist"
LANDING_PAGE = WEB_ROOT / "index.html"
REQUIREMENTS_PATH = WEB_ROOT / "requirements.txt"
HOME_ROOT = WEB_ROOT / ".home"
CLANG_TOOLCHAIN_ROOT = HOME_ROOT / ".clang-tool-chain"
TOOLCHAIN_SHIM_ROOT = WEB_ROOT / ".toolchain-shims"
FASTLED_CACHE_ROOT = WEB_ROOT / ".fastled"
FASTLED_VERSION = "3.10.3"
FASTLED_ARCHIVE_URL = f"https://github.com/FastLED/FastLED/archive/refs/tags/{FASTLED_VERSION}.zip"
FASTLED_LIBRARY_ROOT = FASTLED_CACHE_ROOT / f"FastLED-{FASTLED_VERSION}"
SOURCE_WRAPPER_PREFIX = "polarshader_unit_"
PLACEHOLDER_FRONTEND_MARKER = 'module._extern_setup();'
MINIMAL_FRONTEND_MARKERS = (
    "const canvas = document.getElementById('canvas');",
    "FastLED WASM",
)

EXCLUDED_SOURCE_FILES = {
    "FastLED.h",
    "main_samd.cpp",
    "main_teensy.cpp",
    "main_rp2040_fabric.cpp",
    "main_rp2040_round.cpp",
}

EXCLUDED_SOURCE_DIRS = {
    "native",
}

EXCLUDED_WRAPPER_SOURCE_PATHS = {
    "display/src/SmartMatrixDisplay.cpp",
}


def pinned_fastled_cli_version() -> str:
    prefix = "fastled=="
    for requirement in REQUIREMENTS_PATH.read_text(encoding="utf-8").splitlines():
        normalized_requirement = requirement.split("#", 1)[0].strip()
        if normalized_requirement.startswith(prefix):
            return normalized_requirement[len(prefix):].strip()

    raise SystemExit(f"Missing pinned fastled CLI version in {REQUIREMENTS_PATH}")


FASTLED_CLI_VERSION = pinned_fastled_cli_version()


@dataclass(frozen=True)
class Sketch:
    name: str
    source_file: Path


SKETCHES = (
    Sketch("fabric", SKETCH_ROOT / "fabric" / "fabric.ino"),
    Sketch("round", SKETCH_ROOT / "round" / "round.ino"),
)


def reset_directory(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def copy_tree_without_platform_entrypoints(stage_dir: Path) -> None:
    for child in SOURCE_ROOT.iterdir():
        if child.name in EXCLUDED_SOURCE_DIRS:
            continue

        destination = stage_dir / child.name
        if child.is_dir():
            shutil.copytree(
                child,
                destination,
                ignore=shutil.ignore_patterns("SmartMatrixDisplay.cpp"),
            )
            continue

        if child.name in EXCLUDED_SOURCE_FILES:
            continue

        shutil.copy2(child, destination)


def list_wrapper_source_files(stage_dir: Path) -> list[str]:
    source_files: list[str] = []
    for source_path in sorted(stage_dir.rglob("*.cpp")):
        relative_path = source_path.relative_to(stage_dir).as_posix()
        if relative_path in EXCLUDED_WRAPPER_SOURCE_PATHS:
            continue
        source_files.append(relative_path)
    return source_files


def write_source_wrappers(stage_dir: Path) -> None:
    for index, source_path in enumerate(list_wrapper_source_files(stage_dir)):
        wrapper_path = stage_dir / f"{SOURCE_WRAPPER_PREFIX}{index:03d}.cpp"
        wrapper_path.write_text(
            "\n".join(
                [
                    "// Auto-generated by web/build_site.py.",
                    f'#include "{source_path}"',
                    "",
                ]
            ),
            encoding="utf-8",
        )


def stage_sketch(sketch: Sketch) -> Path:
    stage_dir = STAGE_ROOT / sketch.name
    reset_directory(stage_dir)
    copy_tree_without_platform_entrypoints(stage_dir)
    write_source_wrappers(stage_dir)
    shutil.copy2(sketch.source_file, stage_dir / f"{sketch.name}.ino")
    return stage_dir


def fastled_version(path: Path) -> str | None:
    metadata_path = path / "library.json"
    if not metadata_path.exists():
        return None

    with metadata_path.open(encoding="utf-8") as metadata_file:
        metadata = json.load(metadata_file)

    version = metadata.get("version")
    return version if isinstance(version, str) else None


def disable_fastled_wasm_build_system(fastled_dir: Path) -> None:
    wasm_build_script = fastled_dir / "ci" / "wasm_build.py"
    disabled_script = fastled_dir / "ci" / "wasm_build.py.disabled"

    if not wasm_build_script.exists():
        return
    if disabled_script.exists():
        disabled_script.unlink()
    wasm_build_script.rename(disabled_script)


def remove_placeholder_frontend_dist(fastled_dir: Path) -> None:
    dist_dir = fastled_dir / "src" / "platforms" / "wasm" / "compiler" / "dist"
    index_path = dist_dir / "index.html"
    if not index_path.exists():
        return

    index_text = index_path.read_text(encoding="utf-8")
    if PLACEHOLDER_FRONTEND_MARKER in index_text:
        shutil.rmtree(dist_dir)


def normalize_fastled_library(fastled_dir: Path) -> Path:
    disable_fastled_wasm_build_system(fastled_dir)
    remove_placeholder_frontend_dist(fastled_dir)
    return fastled_dir


def download_fastled_source(destination_dir: Path) -> None:
    FASTLED_CACHE_ROOT.mkdir(parents=True, exist_ok=True)
    if destination_dir.exists():
        shutil.rmtree(destination_dir)

    with tempfile.TemporaryDirectory(dir=FASTLED_CACHE_ROOT) as temp_dir_name:
        archive_path = Path(temp_dir_name) / f"FastLED-{FASTLED_VERSION}.zip"
        with urllib.request.urlopen(FASTLED_ARCHIVE_URL) as response, archive_path.open("wb") as archive_file:
            shutil.copyfileobj(response, archive_file)

        with zipfile.ZipFile(archive_path) as archive:
            archive.extractall(FASTLED_CACHE_ROOT)

    extracted_dir = FASTLED_CACHE_ROOT / f"FastLED-{FASTLED_VERSION}"
    if extracted_dir != destination_dir:
        extracted_dir.rename(destination_dir)


def ensure_fastled_library() -> Path:
    if fastled_version(FASTLED_LIBRARY_ROOT) == FASTLED_VERSION:
        return normalize_fastled_library(FASTLED_LIBRARY_ROOT)

    download_fastled_source(FASTLED_LIBRARY_ROOT)
    return normalize_fastled_library(FASTLED_LIBRARY_ROOT)


def fastled_cli_version(executable: Path) -> str | None:
    try:
        completed = subprocess.run(
            [str(executable), "--version"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None

    version_output = "\n".join(
        output.strip()
        for output in (completed.stdout, completed.stderr)
        if output.strip()
    )
    if not version_output:
        return None

    version_match = re.search(r"\b\d+\.\d+\.\d+(?:[A-Za-z0-9._+-]*)\b", version_output)
    return version_match.group(0) if version_match else version_output.splitlines()[0]


def resolve_fastled_executable() -> str:
    candidate_names = ("fastled.exe", "fastled") if os.name == "nt" else ("fastled",)
    candidate_paths: list[Path] = []

    for candidate_name in candidate_names:
        candidate_paths.append(Path(sys.executable).parent / candidate_name)

    path_candidate = shutil.which("fastled")
    if path_candidate is not None:
        candidate_paths.append(Path(path_candidate))

    checked_paths: set[str] = set()
    mismatched_versions: list[tuple[Path, str]] = []
    for candidate_path in candidate_paths:
        candidate_key = str(candidate_path)
        if candidate_key in checked_paths:
            continue
        checked_paths.add(candidate_key)

        version = fastled_cli_version(candidate_path)
        if version is None:
            continue
        if version == FASTLED_CLI_VERSION:
            return str(candidate_path)
        mismatched_versions.append((candidate_path, version))

    mismatch_hint = ""
    if mismatched_versions:
        mismatched_path, mismatched_version = mismatched_versions[0]
        mismatch_hint = f" Found {mismatched_path} reporting version {mismatched_version}."

    raise SystemExit(
        f"fastled CLI {FASTLED_CLI_VERSION} not found for {sys.executable}. "
        f"Install it with `{sys.executable} -m pip install -r {REQUIREMENTS_PATH}`."
        f"{mismatch_hint}"
    )


def run_fastled_compile(stage_dir: Path) -> None:
    HOME_ROOT.mkdir(parents=True, exist_ok=True)
    CLANG_TOOLCHAIN_ROOT.mkdir(parents=True, exist_ok=True)
    TOOLCHAIN_SHIM_ROOT.mkdir(parents=True, exist_ok=True)

    emcc_shim = TOOLCHAIN_SHIM_ROOT / "clang-tool-chain-emcc"
    emar_shim = TOOLCHAIN_SHIM_ROOT / "clang-tool-chain-emar"
    for shim_path, tool_name in ((emcc_shim, "emcc"), (emar_shim, "emar")):
        shim_path.write_text(
            "\n".join(
                [
                    "#!/bin/sh",
                    "set -eu",
                    f'for candidate in "{CLANG_TOOLCHAIN_ROOT}"/emscripten/*/*/emscripten/{tool_name} "{CLANG_TOOLCHAIN_ROOT}"/emscripten/*/emscripten/{tool_name}; do',
                    '  if [ -x "$candidate" ]; then',
                    '    exec "$candidate" "$@"',
                    "  fi",
                    "done",
                    f'echo "Unable to find {tool_name} inside {CLANG_TOOLCHAIN_ROOT}." >&2',
                    "exit 1",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        shim_path.chmod(0o755)

    fastled_library = ensure_fastled_library()
    fastled_executable = resolve_fastled_executable()

    command = [
        fastled_executable,
        str(stage_dir),
        "--just-compile",
        "--release",
        "--fastled-path",
        str(fastled_library),
    ]

    env = dict(os.environ)
    env["HOME"] = str(HOME_ROOT)
    env["CLANG_TOOL_CHAIN_DOWNLOAD_PATH"] = str(CLANG_TOOLCHAIN_ROOT)
    env["PATH"] = f"{TOOLCHAIN_SHIM_ROOT}{os.pathsep}{env.get('PATH', '')}"

    subprocess.run(
        command,
        cwd=stage_dir,
        check=True,
        env=env,
    )


def find_build_output(stage_dir: Path) -> Path:
    preferred_dirs = (
        stage_dir / "fastled_js",
        stage_dir / "build",
        stage_dir / "out",
    )

    for candidate in preferred_dirs:
        if (candidate / "index.html").exists():
            return candidate

    built_pages = [path.parent for path in stage_dir.rglob("index.html")]
    if not built_pages:
        raise FileNotFoundError(f"Could not find FastLED build output in {stage_dir}")

    return max(built_pages, key=lambda path: path.stat().st_mtime)


def validate_frontend_output(output_dir: Path) -> None:
    index_path = output_dir / "index.html"
    if not index_path.exists():
        raise FileNotFoundError(f"Missing frontend index at {index_path}")

    index_text = index_path.read_text(encoding="utf-8")
    if PLACEHOLDER_FRONTEND_MARKER in index_text and any(
        marker in index_text for marker in MINIMAL_FRONTEND_MARKERS
    ):
        raise RuntimeError(
            "FastLED frontend assets were not built; refusing to publish the minimal fallback page."
        )


def build_site() -> None:
    reset_directory(STAGE_ROOT)
    reset_directory(DIST_ROOT)

    for sketch in SKETCHES:
        stage_dir = stage_sketch(sketch)
        run_fastled_compile(stage_dir)
        output_dir = find_build_output(stage_dir)
        validate_frontend_output(output_dir)
        shutil.copytree(output_dir, DIST_ROOT / sketch.name)

    shutil.copy2(LANDING_PAGE, DIST_ROOT / "index.html")


def main() -> int:
    build_site()
    return 0


if __name__ == "__main__":
    sys.exit(main())
